version: '3.3'

services:
  automation:
    image: broyal/mtaci_jenkins:${VERSION}
    ports:
      - "8080:8080"
    volumes:
      - automation_config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
#      placement:
#        constraints:
#          - 'node.role == manager'
    environment:
      - INTERNAL_REPOSITORY_PATH=http://git:3000/mta/app1.git
    networks:
      - ci
    secrets:
      - jenkins-user
      - jenkins-pass
  
  git:
    image: broyal/mtaci_gogs:${VERSION}
    ports:
      - "3000:3000"
    volumes:
      - git_config:/data
    deploy:
      mode: replicated
#      placement:
#        constraints:
#          - 'node.role == manager'
    networks:
      - ci
      - git_db
    configs:
      - gogs_app_ini

  git_db:
    image: broyal/mtaci_gogs_db:${VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword1 #TODO: point to secret
    volumes:
      - db_db:/var/lib/mysql
    deploy:
      mode: replicated
#      placement:
#        constraints:
#          - 'node.role == manager'
    networks:
      - ci
      - git_db

networks:
  ci:
    driver: overlay
  git_db:
    driver: overlay

volumes:
  automation_config:
  git_config:
  db_db:

configs:
  gogs_app_ini:
    file: ./configs/git/app.ini

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
